# Project metadata
sonar.projectKey=myweb
sonar.projectName=MyWeb Application
sonar.projectVersion=8.7.3

# Source code and tests
sonar.sources=src/main/java
sonar.tests=src/test/java

# Web resources (JSP, HTML, JS, CSS)
sonar.sources=src/main/webapp

# Compiled bytecode location
sonar.java.binaries=target/classes

# Coverage report (JaCoCo plugin generates this)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# SonarQube server connection
sonar.host.url=http://44.211.42.138:9000/:9000
sonar.token=sqa_97a343024c68059362d814908c0e55a4fc3f3730
