sonar.projectKey=one
sonar.projectName=One Project
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://18.233.7.23:9000
sonar.login=sqa_86f5e2a32b6cbfae40687e378ae7417fc2811886
